"""
visualize.py

Visualization utilities for inspecting coarse-grained molecular assemblies
detected from PDB/mmCIF files.

This module renders:
- Molecule centers (COMs) as spheres
- Interfaces as smaller colored markers
- Interface connections (optional) as lines/arcs
- Labels for molecules and interfaces

Requires `matplotlib` and `mpl_toolkits.mplot3d` for 3D rendering.

Functions
---------
- plot_coarse_grain_model(model, show_reactions=False)
- plot_interfaces(ax, coords, color, label=None)
"""
import os
import matplotlib.pyplot as plt
import numpy as np


def plot_interfaces(ax, coords, color="red", label=None, size=40):
    """
    Plot spherical markers at interface positions.

    Parameters
    ----------
    ax : Axes3D
        The matplotlib 3D axis to draw on.
    coords : list of (3,) ndarray
        Coordinates of interface positions.
    color : str
        Color for marker.
    label : str or None
        Optional label for the group of interfaces.
    size : int
        Marker size.
    """
    coords = np.array([com.to_numpy() for com in coords])
    print(coords)
    ax.scatter(coords[:, 0], coords[:, 1], coords[:, 2],
               c=color, s=size, label=label)


def plot_coarse_grain_model(model, show_reactions=False, figsize=(10, 8), elev=30, azim=30):
    """
    Render a 3D plot of the coarse-grained model.

    Parameters
    ----------
    model : dict
        The regularized model output from `regularize_model()`, containing:
        - 'COMs', 'interface_coords', 'interfaces', 'chain_ids', etc.
    show_reactions : bool
        If True, draw lines between each interface pair.
    figsize : tuple
        Size of the matplotlib figure.
    elev : float
        Elevation angle for 3D view.
    azim : float
        Azimuthal angle for 3D view.
    """
    fig = plt.figure(figsize=figsize)
    ax = fig.add_subplot(111, projection='3d')

    coms = np.array([com.to_numpy() for com in model["COMs"]])
    ax.scatter(coms[:, 0], coms[:, 1], coms[:, 2],
               c="black", s=80, label="COMs")

    # Plot interfaces for each chain
    for i, iface_coords in enumerate(model["interface_coords"]):
        plot_interfaces(ax, iface_coords, color="red")
        com = model["COMs"][i]
        for interface in iface_coords:
            # Plot the bond between coms and interface
            x, y, z = zip(interface, com)
            ax.plot(x, y, z, "gray", linewidth=1)

    # Optionally draw edges between interfaces
    if show_reactions:
        for i, neighbors in enumerate(model["interfaces"]):
            for j, neighbor in enumerate(neighbors):
                if i < neighbor:
                    coord1 = model["interface_coords"][i][j]
                    # Find back-link index
                    try:
                        k = model["interfaces"][neighbor].index(i)
                        coord2 = model["interface_coords"][neighbor][k]
                        x, y, z = zip(coord1, coord2)
                        ax.plot(x, y, z, "gray", linewidth=1)
                    except ValueError:
                        continue

    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.view_init(elev=elev, azim=azim)
    ax.legend()
    ax.set_aspect('equal')
    plt.tight_layout()
    plt.show()


def save_original_coarse_grained_structure(cg_model,
                                           save_dir, pdb_file,
                                           output_cif: str = "original_coarse_grained_structure.cif",
                                           pymol_script: str = "original_visualize_coarse_grained.pml"):
    """Saves the original coarse-grained structure (COM and interface coordinates for each chain)
    to a CIF file and generates a PyMOL script for quick visualization.

    Args:
        output_cif (str, optional): Output .cif filename. Defaults to "original_coarse_grained_structure.cif".
        pymol_script (str, optional): Output .pml filename for PyMOL. Defaults to "original_visualize_coarse_grained.pml".
    """
    output_cif = os.path.join(save_dir, output_cif)
    pymol_script = os.path.join(save_dir, pymol_script)

    with open(output_cif, 'w', encoding="utf-8") as cif_file:
        atom_id = 1

        # Write CIF header
        cif_file.write("# Coarse-grained structure CIF file\n")
        cif_file.write("data_coarse_grained\n")
        cif_file.write(
            "_audit_conform_dict.text 'Original coarse-grained model generated by ionerdss'\n")
        cif_file.write("loop_\n")
        cif_file.write("_atom_site.group_PDB\n")
        cif_file.write("_atom_site.id\n")
        cif_file.write("_atom_site.label_atom_id\n")
        cif_file.write("_atom_site.label_comp_id\n")
        cif_file.write("_atom_site.label_asym_id\n")
        cif_file.write("_atom_site.Cartn_x\n")
        cif_file.write("_atom_site.Cartn_y\n")
        cif_file.write("_atom_site.Cartn_z\n")
        cif_file.write("_atom_site.occupancy\n")
        cif_file.write("_atom_site.B_iso_or_equiv\n")
        cif_file.write("_atom_site.type_symbol\n")

        # Write COM atoms for each chain
        for i, chain in enumerate(cg_model["chains"]):
            if not cg_model["COMs"][i]:
                continue
            com = cg_model["COMs"][i]
            cif_file.write(
                f"ATOM  {atom_id:5d}  COM  MOL {chain.id}  "
                f"{com.x:8.3f} {com.y:8.3f} {com.z:8.3f}  1.00  0.00  C\n"
            )
            atom_id += 1

            # Write interface atoms for the current chain
            for j, interface_coord in enumerate(cg_model["interface_coords"][i]):
                cif_file.write(
                    f"ATOM  {atom_id:5d}  INT  MOL {chain.id}  "
                    f"{interface_coord.x:8.3f} {interface_coord.y:8.3f} {interface_coord.z:8.3f}  1.00  0.00  O\n"
                )
                atom_id += 1

    print(f"Coarse-grained structure saved to {output_cif}.")

    # Generate PyMOL script for visualization
    with open(pymol_script, 'w', encoding="utf-8") as pml_file:
        pml_file.write(
            "# PyMOL script to visualize coarse-grained structure\n")
        pml_file.write(f"load {output_cif}, coarse_grained\n")
        pml_file.write("hide everything\n")
        pml_file.write("show spheres, name COM\n")
        pml_file.write("show spheres, name INT\n")
        pml_file.write("set sphere_scale, 1.0\n")
        pml_file.write("color red, name COM\n")
        pml_file.write("color blue, name INT\n")

        # Create pseudo-atoms for COM and interfaces and draw lines
        atom_index = 1
        for i, chain in enumerate(cg_model["chains"]):
            com = cg_model["COMs"][i]
            if not com:
                continue
            # Make a pseudoatom for the chain's COM
            pml_file.write(
                f"pseudoatom com_{chain.id}, pos=[{com.x:.3f}, {com.y:.3f}, {com.z:.3f}], color=red\n"
            )

            # For each interface, create a pseudoatom and connect it to the COM
            for j, interface_coord in enumerate(cg_model["interface_coords"][i], start=1):
                pml_file.write(
                    f"pseudoatom int_{chain.id}_{j}, pos=[{interface_coord.x:.3f}, "
                    f"{interface_coord.y:.3f}, {interface_coord.z:.3f}], color=blue\n"
                )
                # Use f-strings so {atom_index} is replaced numerically
                pml_file.write(
                    f"distance line{atom_index}, com_{chain.id}, int_{chain.id}_{j}\n")
                pml_file.write(f"set dash_width, 4, line{atom_index}\n")
                pml_file.write(f"set dash_gap, 0.5, line{atom_index}\n")
                atom_index += 1

        pml_file.write("set sphere_transparency, 0.2\n")
        pml_file.write("bg_color white\n")
        pml_file.write("zoom all\n")

        pml_file.write(f"load {pdb_file}\n")
        pml_file.write("spectrum chain\n")
        pdb_file = os.path.basename(pdb_file).split('.')[0]
        pml_file.write(f"hide everything, {pdb_file}\n")
        pml_file.write(f"show cartoon, {pdb_file}\n")
        pml_file.write(f"set cartoon_transparency, 0.7, {pdb_file}\n")
        save_figure = os.path.join(save_dir, "comparison_initial.png")
        pml_file.write(f"png {save_figure}, 800, 800, 150, 1\n")

    print(
        f"PyMOL script saved to {pymol_script}. Run 'pymol {pymol_script}' to visualize the coarse-grained structure.")
