[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ioNERDSS"
version = "1.2.0"
description = "Package for preparing NERDSS inputs and analysing outputs."
readme = "README.md"
license = { text = "GPL-3.0" }
authors = [
    { name = "Yue Moon Ying", email = "yying7@jh.edu"},
    { name = "Samuel L Foley", email = "sfoley13@jh.edu"},
    { name = "Zixiu (Hugh) Liu", email = "zliu140@jhu.edu" },
    { name = "Sikao Guo", email = "sikaoguo@gmail.com" },
    { name = "Mankun Sang", email = "msang2@jhu.edu" }
]
requires-python = ">=3.10"
keywords = ["NERDSS Simulation", "Model Setup", "Analysis Tools"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3"
]
dependencies = [
    # required for pytorch
    "numpy>=1.26.4, <3",
    "pandas",
    "matplotlib",
    "seaborn",
    "tqdm",
    "PyQt6",
    "pyqtgraph",
    "PyOpenGL",
    "biopython",
    "scipy>=1.13.1, <2",
    "scikit-learn",
    "requests",
    "ipympl",
    "networkx"  # Core dependency for graph-based molecular modeling
]

[project.optional-dependencies]
# Dependencies for running the test suite
test = ["pytest", "pytest-cov"]

# ProAffinity dependcencies
proaffinity = [
  "numpy==1.26.4",
  "scipy==1.13.1",
  "torch==2.2.2",
  "torchvision==0.17.2",
  "torchaudio==2.2.2",
  "torch_geometric==2.3.0",
  "scikit-learn>=1.5.0",
  "transformers==4.38",
  "tokenizers==0.15.2",
  "huggingface-hub>=0.33.2",
  "safetensors>=0.5.3",
  "accelerate>=0.26",
]

# Dependencies for advanced rendering with Ovito
ovito_rendering = ["ovito", "imageio", "Pillow"]

# Dependencies for interactive development (Jupyter notebooks)
jupyter = ["jupyter", "jupyterlab", "ipykernel", "ipywidgets"]

# Dependencies for building documentation
docs = ["furo", "nbsphinx"]

# Install all optional dependencies at once
all = [
    # test dependencies
    "pytest", 
    "pytest-cov",
    # ovito_rendering dependencies
    "ovito", 
    "imageio", 
    "Pillow",
    # jupyter dependencies
    "jupyter", 
    "jupyterlab", 
    "ipykernel", 
    "ipywidgets",
    # docs dependencies
    "furo",
    "nbsphinx",
    # proaffinity
    "ioNERDSS[proaffinity]",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.pytest.ini_options]
testpaths = ["tests"]
