[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ioNERDSS"
version = "2.2"
description = "Package for preparing NERDSS inputs and analysing outputs."
readme = "README.md"
license = { text = "GPL-3.0" }
authors = [
    { name = "Yue Moon Ying", email = "yying7@jh.edu"},
    { name = "Mankun Sang", email = "msang2@jhu.edu" },
    { name = "Samuel L Foley", email = "sfoley13@jh.edu"},
    { name = "Zixiu (Hugh) Liu", email = "zliu140@jhu.edu" },
    { name = "Sikao Guo", email = "sikaoguo@gmail.com" }
]
requires-python = ">=3.10"
keywords = ["NERDSS Simulation", "Model Setup", "Analysis Tools"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3"
]
dependencies = [
    "numpy>=1.26.4, <3",
    "pandas",
    "matplotlib",
    "seaborn",
    "tqdm",
    "PyOpenGL",
    "biopython",
    "scipy>=1.13.1, <2",
    "scikit-learn",
    "requests",
    "ipympl",
    "networkx"
]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

proaffinity = [
  "numpy==1.26.4",
  "scipy==1.13.1",
  "torch==2.2.2",
  "torchvision==0.17.2",
  "torchaudio==2.2.2",
  "torch_geometric==2.3.0",
  "scikit-learn>=1.5.0",
  "transformers==4.38",
  "tokenizers==0.15.2",
  "huggingface-hub>=0.33.2",
  "safetensors>=0.5.3",
  "accelerate>=0.26",
]

ovito_rendering = ["ovito", "imageio", "Pillow"]

jupyter = ["jupyter", "jupyterlab", "ipykernel", "ipywidgets"]

simularium = [
    "simulariumio",
    "MDAnalysis"     # for simulariumio reading NERDSS PDB files
]

docs = [
    "mkdocs>=1.6",
]

all = [
    "pytest",
    "pytest-cov",
    "ovito",
    "imageio",
    "Pillow",
    "jupyter",
    "jupyterlab",
    "ipykernel",
    "ipywidgets",
    "mkdocs>=1.6",
    "ioNERDSS[proaffinity]",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.pytest.ini_options]
testpaths = ["developer_tests"]
