"""
Utility module for converting between Complex objects and NetworkX graphs.

This module provides functions to convert Complex objects to NetworkX graphs
for use with the graph_based submodule, and to generate topology-aware names
for complexes based on their graph structure.
"""

import networkx as nx
from networkx.algorithms.graph_hashing import weisfeiler_lehman_graph_hash
from typing import Dict, List, Tuple, Optional



def complex_to_networkx(complex_obj) -> nx.Graph:
    """
    Convert a Complex object to a NetworkX graph.
    
    Nodes represent molecules with 'type' attribute (molecule template name).
    Edges represent binding interactions with 'type' attribute (interface/reaction name).
    
    Args:
        complex_obj: Complex object from ionerdss.model.complex
        
    Returns:
        nx.Graph: NetworkX graph representation of the complex
    """
    G = nx.Graph()
    
    # Map molecule objects to integer node IDs
    molecules = complex_obj.get_keys()
    mol_to_id = {mol: i for i, mol in enumerate(molecules)}
    
    # Add nodes with molecule type
    for mol_id, mol in enumerate(molecules):
        mol_type = mol.my_template.name if hasattr(mol.my_template, 'name') else mol.name
        G.add_node(mol_id, type=mol_type)
    
    # Add edges with reaction/interface type
    added_edges = set()
    for mol in molecules:
        mol_id = mol_to_id[mol]
        for partner, reaction in complex_obj.get_interactions(mol):
            if partner is None:
                continue
            
            partner_id = mol_to_id[partner]
            
            # Avoid duplicate edges (undirected graph)
            edge_key = tuple(sorted([mol_id, partner_id]))
            if edge_key in added_edges:
                continue
            
            # Use reaction template expression as edge type
            edge_type = reaction.my_template.expression if hasattr(reaction.my_template, 'expression') else "binding"
            G.add_edge(mol_id, partner_id, type=edge_type)
            added_edges.add(edge_key)
    
    return G


def generate_complex_name_from_graph(G: nx.Graph, use_hash: bool = True) -> str:
    """
    Generate a human-readable name from a NetworkX graph representing a complex.
    
    The name encodes:
    - Node types (sorted)
    - Graph topology (linear, cyclic, branched, complete)
    - Weisfeiler-Lehman hash for uniqueness (optional)
    
    Args:
        G: NetworkX graph
        use_hash: Whether to include WL hash for uniqueness
        
    Returns:
        str: Complex name (e.g., "A3_B1_linear_8f2a" or "X4_complete")
    """
    if len(G.nodes) == 0:
        return "empty"
    
    # Single node complex
    if len(G.nodes) == 1:
        node_data = list(G.nodes(data=True))[0][1]
        node_type = node_data.get('type', 'unknown')
        return node_type
    
    # Get node type composition
    node_types = [data.get('type', 'unknown') for _, data in G.nodes(data=True)]
    type_counts = {}
    for t in node_types:
        type_counts[t] = type_counts.get(t, 0) + 1
    
    # Sort by type name for consistency
    sorted_types = sorted(type_counts.items())
    composition = '_'.join(f"{t}{count}" for t, count in sorted_types)
    
    # Determine topology
    topology = _classify_topology(G)
    
    # Generate WL hash for uniqueness
    if use_hash:
        # Relabel to integers for consistent hashing
        G_relabeled = nx.convert_node_labels_to_integers(G)
        wl_hash = weisfeiler_lehman_graph_hash(G_relabeled, node_attr='type', edge_attr='type')
        # Take last 4 characters of hash for brevity
        hash_suffix = str(abs(hash(wl_hash)) % 10000).zfill(4)
        return f"{composition}_{topology}_{hash_suffix}"
    else:
        return f"{composition}_{topology}"


def _classify_topology(G: nx.Graph) -> str:
    """
    Classify the topology of a graph.
    
    Returns:
        str: One of "linear", "cyclic", "star", "complete", "branched", "disconnected"
    """
    if not nx.is_connected(G):
        return "disconnected"
    
    n_nodes = len(G.nodes)
    n_edges = len(G.edges)
    degrees = [deg for _, deg in G.degree()]
    
    # Complete graph
    if n_edges == n_nodes * (n_nodes - 1) // 2:
        return "complete"
    
    # Tree (connected acyclic)
    if n_edges == n_nodes - 1:
        # Linear (path)
        if degrees.count(2) == n_nodes - 2 and degrees.count(1) == 2:
            return "linear"
        # Star
        elif degrees.count(1) == n_nodes - 1 and degrees.count(n_nodes - 1) == 1:
            return "star"
        else:
            return "tree"
    
    # Cycle
    if n_edges == n_nodes and all(deg == 2 for deg in degrees):
        return "cyclic"
    
    # Branched (has cycles or branching points)
    return "branched"


def networkx_to_complex(G: nx.Graph, pdb_model=None):
    """
    Convert a NetworkX graph back to a Complex object.
    
    This is used to convert subgraphs generated by get_unique_fully_connected_subgraphs()
    back into Complex objects for the ODE system.
    
    Args:
        G: NetworkX graph with 'type' attributes on nodes and edges
        pdb_model: Optional PDBModel to look up actual molecule and reaction objects
        
    Returns:
        Complex: A new Complex object representing the graph
    """
    from .complex import Complex
    
    if len(G.nodes) == 0:
        return Complex()
    
    complex_obj = Complex()
    
    # Create mock molecule objects for now
    # In practice, we would look these up from pdb_model
    node_to_mol = {}
    for node_id, node_data in G.nodes(data=True):
        mol_type = node_data.get('type', 'unknown')
        # Create a minimal mock molecule
        # This would be replaced with actual molecule lookup in integration
        mock_mol = type('MockMolecule', (), {
            'name': f"{mol_type}_{node_id}",
            'my_template': type('MockTemplate', (), {'name': mol_type})()
        })()
        node_to_mol[node_id] = mock_mol
    
    # Add interactions based on edges
    for u, v, edge_data in G.edges(data=True):
        mol_u = node_to_mol[u]
        mol_v = node_to_mol[v]
        
        # Create mock reaction
        edge_type = edge_data.get('type', 'binding')
        mock_reaction = type('MockReaction', (), {
            'my_template': type('MockTemplate', (), {'expression': edge_type})()
        })()
        
        # Add bidirectional interactions
        complex_obj.add_interaction(mol_u, mol_v, mock_reaction)
        complex_obj.add_interaction(mol_v, mol_u, mock_reaction)
    
    # For single molecule complexes
    if len(G.nodes) == 1 and len(G.edges) == 0:
        mol = node_to_mol[list(G.nodes)[0]]
        complex_obj.add_interaction(mol, None, None)
    
    return complex_obj


def get_subgraphs_from_complex(complex_obj, pdb_model=None) -> List[nx.Graph]:
    """
    Generate all unique fully connected subgraphs from a complex.
    
    Uses get_unique_fully_connected_subgraphs() from graph_based module.
    
    Args:
        complex_obj: Complex object to generate subgraphs from
        pdb_model: Optional PDBModel for context
        
    Returns:
        List[nx.Graph]: List of unique subgraph structures
    """
    from ionerdss.model.graph_based.complexes.subcomplexes import get_unique_fully_connected_subgraphs
    
    # Convert complex to graph
    G = complex_to_networkx(complex_obj)
    
    # Get all unique subgraphs
    subgraphs = get_unique_fully_connected_subgraphs(G)
    
    return subgraphs
